In [1]:
import numpy as np
import pandas as pd


answer_data = pd.read_csv('answer_data_2_4.csv')
user_data = pd.read_csv('document_data_2_4.csv')

# question_types
question_types = ['성장환경', '전공, 과목', '취미, 특기', '성격의 장/단점', '역량, 강점', 
     '지원동기', '입사 후 포부, 계획, 기여하고 싶은 부분', '프로젝트 경험', '사회활동',
     '어려움 극복, 목표 달성 경험', '의사소통', '문제 해결', '팀워크, 협업(동아리, 팀) 경험', 
     '창의성', '리더쉽 발휘', '도전', '자기소개', '가치관', '사회 현상 및 트렌드(최근 뉴스, 국내외 이슈 견해)', 
     '인재상, 기업의 핵심 가치, 기업의 이미지', '경력', '기타']

# company
companies = list(user_data.company.unique())

# major_large
major_larges = list(user_data.major_large.unique())

# major_small
major_smalls = list(user_data.major_small.unique())

# job_large
job_larges = list(user_data.job_type.unique())

# job_small
job_smalls = list(user_data.job.unique())

# recommendtype은 아직 안정해짐
recommend_types = []

In [2]:
major_dict = dict(user_data.groupby('major_small')['major_large'].apply(set).apply(list))
job_dict = dict(user_data.groupby('job')['job_type'].apply(set).apply(list))

In [3]:
major_dict

{'IT/컴퓨터공학': ['자연/공학/의약계열'],
 '간호학': ['자연/공학/의약계열'],
 '건축공학': ['자연/공학/의약계열'],
 '경영학': ['인문/사회계열'],
 '경제학': ['인문/사회계열'],
 '광고/홍보': ['인문/사회계열'],
 '교육계열(문과)': ['교육계열'],
 '교육계열(예체능)': ['교육계열'],
 '교육계열(이과)': ['교육계열'],
 '교육학': ['교육계열'],
 '국제통상/경상': ['인문/사회계열'],
 '금속/신소재공학': ['자연/공학/의약계열'],
 '금융': ['인문/사회계열'],
 '기계/항공': ['자연/공학/의약계열'],
 '기타': ['기타'],
 '도시공학': ['자연/공학/의약계열'],
 '독어/독문': ['인문/사회계열'],
 '문헌정보학': ['인문/사회계열'],
 '물리학': ['자연/공학/의약계열'],
 '미디어': ['인문/사회계열'],
 '반도체/디스플레이': ['자연/공학/의약계열'],
 '법학': ['인문/사회계열'],
 '사이버보안학': ['자연/공학/의약계열'],
 '사회계열(기타)': ['인문/사회계열'],
 '사회복지학': ['인문/사회계열'],
 '사회학': ['인문/사회계열'],
 '산업/제품디자인': ['예체능계열'],
 '산업공학': ['자연/공학/의약계열'],
 '상경계열(기타)': ['인문/사회계열'],
 '생물공학': ['자연/공학/의약계열'],
 '서어/서문': ['인문/사회계열'],
 '세무/회계': ['인문/사회계열'],
 '수학/통계학': ['자연/공학/의약계열'],
 '스포츠과학': ['자연/공학/의약계열'],
 '식품영양학': ['자연/공학/의약계열'],
 '신문방송/언론정보학': ['인문/사회계열'],
 '심리학': ['인문/사회계열'],
 '에너지/원자력 공학': ['자연/공학/의약계열'],
 '역사/한국사학': ['인문/사회계열'],
 '영어/영문': ['인문/사회계열'],
 '예체능계열(기타)': ['예체능계열'],
 '의류/패션디자인': ['예체능계열'],
 '인문계열(기타)': ['인문/사회계열'],
 '일어/일문': ['인문/사회계열'],
 '자동차공학': ['자연/공학/의약계열'],
 '자연/공학/의약계열(기타)': ['자연/공학/의약계열'],
 '재료공학': ['자연/공학/의약계열'],
 '전자전기공학': ['자연/공학/의약계열'],
 '정보통신학': ['자연/공학/의약계열'],
 '정치외교학': ['인문/사회계열'],
 '조경학': ['자연/공학/의약계열'],
 '조선해양공학': ['자연/공학/의약계열'],
 '중어/중문': ['인문/사회계열'],
 '지구환경공학': ['자연/공학/의약계열'],
 '철학': ['인문/사회계열'],
 '토목공학': ['자연/공학/의약계열'],
 '프어/프문': ['인문/사회계열'],
 '행정학': ['인문/사회계열'],
 '호텔경영학': ['인문/사회계열'],
 '화학': ['자연/공학/의약계열'],
 '화학공학/생명공학': ['자연/공학/의약계열']}

In [4]:
major_dict['간호학']

['자연/공학/의약계열']

In [5]:
doc_pro_rating = answer_data.groupby('user_id')['score'].apply(set).apply(list)

In [6]:
doc_pro_rating.keys()

Int64Index([   2,    3,    4,    5,    6,    7,    8,   10,   12,   13,
            ...
            7110, 7113, 7115, 7116, 7118, 7120, 7121, 7124, 7126, 7127],
           dtype='int64', name='user_id', length=4614)

In [7]:
user_data

,user_id,major_large,major_small,company,season,job,school,extra_spec,job_type
0,1,인문/사회계열,세무/회계,초석건설산업(주),2015년 상반기,기획·전략·경영,해외대학,"['학점 3.5/4.5', '토익 915', '해외경험 2회']",경영·사무
1,2,자연/공학/의약계열,자연/공학/의약계열(기타),LG디스플레이,2016년 상반기,생산관리·공정관리·품질관리,수도권4년,"['학점 3.8/4.5', '토익 895', '토스 Level6', '오픽 M1',...",생산·제조
2,3,자연/공학/의약계열,IT/컴퓨터공학,롯데IT테크(주),2015년 하반기,응용프로그래머,수도권4년,"['학점 3.5/4.5', '토익 780', '토스 Level4']",IT·인터넷
3,4,인문/사회계열,인문계열(기타),홈플러스(주),2022년 하반기,판매·서빙·매장관리,대졸4년,"['학점 4.5/4.5', '제2외국어 3개', '자격증 4개', '해외경험 1회'...",영업·고객상담
4,5,인문/사회계열,경영학,㈜노루페인트,2015년 상반기,마케팅·광고·분석,지방4년,"['학점 3.7/4.5', '토익 825', '자격증 1개', '인턴 1회', '수...",마케팅·광고·홍보
...,...,...,...,...,...,...,...,...,...
7122,7123,자연/공학/의약계열,IT/컴퓨터공학,㈜티맥스소프트,2015년 상반기,응용프로그래머,수도권4년,"['학점 3.3/4.5', '토익 865', '토스 Level6', '수상 1회']",IT·인터넷
7123,7124,자연/공학/의약계열,IT/컴퓨터공학,GS리테일,2015년 상반기,시스템프로그래머,수도권4년,"['학점 3.7/4.5', '토익 735', '오픽 IH', '자격증 4개', '해...",IT·인터넷
7124,7125,인문/사회계열,경제학,㈜하나투어,2015년 하반기,영업관리·지원·영업기획,서울4년,"['학점 3/4.5', '토익 840', '토스 Level6', '자격증 4개']",영업·고객상담
7125,7126,인문/사회계열,역사/한국사학,현대백화점,2019년 하반기,마케팅·광고·분석,지방4년,"['학점 4/4.5', '토익 965', '오픽 IH', '자격증 3개', '수상 ...",마케팅·광고·홍보
7126,7127,인문/사회계열,경제학,신한카드(주),2015년 하반기,고객상담·인바운드,지방4년,"['학점 3.9/4.5', '토익 690', '자격증 4개', '자원봉사 1회']",영업·고객상담

In [8]:
doc_who_answer = doc_pro_rating.keys()
for i in range(1, 7128):
    if i in doc_who_answer:
        user_data.loc[user_data['user_id']==i, 'pro_rating'] = doc_pro_rating[i][0]
    else:
        user_data.loc[user_data['user_id']==i, 'pro_rating'] = -1

In [9]:
doc_pro_rating

user_id
2       [-1.0]
3       [-1.0]
4       [-1.0]
5       [-1.0]
6        [3.0]
         ...
7120    [-1.0]
7121     [3.0]
7124    [-1.0]
7126     [2.0]
7127    [-1.0]
Name: score, Length: 4614, dtype: object

In [10]:
doc_who_answer

Int64Index([   2,    3,    4,    5,    6,    7,    8,   10,   12,   13,
            ...
            7110, 7113, 7115, 7116, 7118, 7120, 7121, 7124, 7126, 7127],
           dtype='int64', name='user_id', length=4614)

In [19]:
user_data

,user_id,major_large,major_small,company,season,job,school,extra_spec,job_type,pro_rating
0,1,인문/사회계열,세무/회계,초석건설산업(주),2015년 상반기,기획·전략·경영,해외대학,"['학점 3.5/4.5', '토익 915', '해외경험 2회']",경영·사무,-1.0
1,2,자연/공학/의약계열,자연/공학/의약계열(기타),LG디스플레이,2016년 상반기,생산관리·공정관리·품질관리,수도권4년,"['학점 3.8/4.5', '토익 895', '토스 Level6', '오픽 M1',...",생산·제조,-1.0
2,3,자연/공학/의약계열,IT/컴퓨터공학,롯데IT테크(주),2015년 하반기,응용프로그래머,수도권4년,"['학점 3.5/4.5', '토익 780', '토스 Level4']",IT·인터넷,-1.0
3,4,인문/사회계열,인문계열(기타),홈플러스(주),2022년 하반기,판매·서빙·매장관리,대졸4년,"['학점 4.5/4.5', '제2외국어 3개', '자격증 4개', '해외경험 1회'...",영업·고객상담,-1.0
4,5,인문/사회계열,경영학,㈜노루페인트,2015년 상반기,마케팅·광고·분석,지방4년,"['학점 3.7/4.5', '토익 825', '자격증 1개', '인턴 1회', '수...",마케팅·광고·홍보,-1.0
...,...,...,...,...,...,...,...,...,...,...
7122,7123,자연/공학/의약계열,IT/컴퓨터공학,㈜티맥스소프트,2015년 상반기,응용프로그래머,수도권4년,"['학점 3.3/4.5', '토익 865', '토스 Level6', '수상 1회']",IT·인터넷,-1.0
7123,7124,자연/공학/의약계열,IT/컴퓨터공학,GS리테일,2015년 상반기,시스템프로그래머,수도권4년,"['학점 3.7/4.5', '토익 735', '오픽 IH', '자격증 4개', '해...",IT·인터넷,-1.0
7124,7125,인문/사회계열,경제학,㈜하나투어,2015년 하반기,영업관리·지원·영업기획,서울4년,"['학점 3/4.5', '토익 840', '토스 Level6', '자격증 4개']",영업·고객상담,-1.0
7125,7126,인문/사회계열,역사/한국사학,현대백화점,2019년 하반기,마케팅·광고·분석,지방4년,"['학점 4/4.5', '토익 965', '오픽 IH', '자격증 3개', '수상 ...",마케팅·광고·홍보,2.0
7126,7127,인문/사회계열,경제학,신한카드(주),2015년 하반기,고객상담·인바운드,지방4년,"['학점 3.9/4.5', '토익 690', '자격증 4개', '자원봉사 1회']",영업·고객상담,-1.0

In [71]:
new_answer_data[new_answer_data["question_category"]=='[]']

NameError: name 'new_answer_data' is not defined

In [20]:
num = 1
result = f'd{num:06}'

In [29]:
tem = answer_data.groupby('user_id')['parsed_url'].apply(set).apply(list)

In [39]:
tem

user_id
2       [https://www.jobkorea.co.kr/starter/PassAssay/...
3       [https://www.jobkorea.co.kr/starter/PassAssay/...
4       [https://www.jobkorea.co.kr/starter/PassAssay/...
5       [https://www.jobkorea.co.kr/starter/PassAssay/...
6       [https://www.jobkorea.co.kr/starter/PassAssay/...
                              ...
7120    [https://www.jobkorea.co.kr/starter/PassAssay/...
7121    [https://www.jobkorea.co.kr/starter/PassAssay/...
7124    [https://www.jobkorea.co.kr/starter/PassAssay/...
7126    [https://www.jobkorea.co.kr/starter/PassAssay/...
7127    [https://www.jobkorea.co.kr/starter/PassAssay/...
Name: parsed_url, Length: 4614, dtype: object

In [40]:
temkey = tem.keys()
for i in range(1, 7128):
    if i in temkey:
        user_data.loc[user_data['user_id']==i, 'doc_url'] = tem[i][0]
    else:
        user_data.loc[user_data['user_id']==i, 'doc_url'] = None

In [45]:
colum_name =list(user_data.columns)

In [47]:
colum_name.pop(0)

'user_id'

In [50]:
colum_name.insert(0, 'doc_id')

In [52]:
user_data.columns = colum_name

In [54]:
user_data.columns = ['doc_id', 'major_large', 'major_small', 'company', 'season', 'job_small', 'school', 'extra_spec', 'job_large', 'pro_rating', 'doc_url']

In [55]:
user_data

,doc_id,major_large,major_small,company,season,job_small,school,extra_spec,job_large,pro_rating,doc_url
0,1,인문/사회계열,세무/회계,초석건설산업(주),2015년 상반기,기획·전략·경영,해외대학,"['학점 3.5/4.5', '토익 915', '해외경험 2회']",경영·사무,-1.0,None
1,2,자연/공학/의약계열,자연/공학/의약계열(기타),LG디스플레이,2016년 상반기,생산관리·공정관리·품질관리,수도권4년,"['학점 3.8/4.5', '토익 895', '토스 Level6', '오픽 M1',...",생산·제조,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
2,3,자연/공학/의약계열,IT/컴퓨터공학,롯데IT테크(주),2015년 하반기,응용프로그래머,수도권4년,"['학점 3.5/4.5', '토익 780', '토스 Level4']",IT·인터넷,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
3,4,인문/사회계열,인문계열(기타),홈플러스(주),2022년 하반기,판매·서빙·매장관리,대졸4년,"['학점 4.5/4.5', '제2외국어 3개', '자격증 4개', '해외경험 1회'...",영업·고객상담,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
4,5,인문/사회계열,경영학,㈜노루페인트,2015년 상반기,마케팅·광고·분석,지방4년,"['학점 3.7/4.5', '토익 825', '자격증 1개', '인턴 1회', '수...",마케팅·광고·홍보,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
...,...,...,...,...,...,...,...,...,...,...,...
7122,7123,자연/공학/의약계열,IT/컴퓨터공학,㈜티맥스소프트,2015년 상반기,응용프로그래머,수도권4년,"['학점 3.3/4.5', '토익 865', '토스 Level6', '수상 1회']",IT·인터넷,-1.0,None
7123,7124,자연/공학/의약계열,IT/컴퓨터공학,GS리테일,2015년 상반기,시스템프로그래머,수도권4년,"['학점 3.7/4.5', '토익 735', '오픽 IH', '자격증 4개', '해...",IT·인터넷,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
7124,7125,인문/사회계열,경제학,㈜하나투어,2015년 하반기,영업관리·지원·영업기획,서울4년,"['학점 3/4.5', '토익 840', '토스 Level6', '자격증 4개']",영업·고객상담,-1.0,None
7125,7126,인문/사회계열,역사/한국사학,현대백화점,2019년 하반기,마케팅·광고·분석,지방4년,"['학점 4/4.5', '토익 965', '오픽 IH', '자격증 3개', '수상 ...",마케팅·광고·홍보,2.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
7126,7127,인문/사회계열,경제학,신한카드(주),2015년 하반기,고객상담·인바운드,지방4년,"['학점 3.9/4.5', '토익 690', '자격증 4개', '자원봉사 1회']",영업·고객상담,-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...

In [56]:
user_data = user_data[['doc_id', 'major_large', 'major_small', 'company', 'season', 'job_large', 'job_small', 'school', 'extra_spec', 'pro_rating', 'doc_url']]

In [57]:
user_data

,doc_id,major_large,major_small,company,season,job_large,job_small,school,extra_spec,pro_rating,doc_url
0,1,인문/사회계열,세무/회계,초석건설산업(주),2015년 상반기,경영·사무,기획·전략·경영,해외대학,"['학점 3.5/4.5', '토익 915', '해외경험 2회']",-1.0,None
1,2,자연/공학/의약계열,자연/공학/의약계열(기타),LG디스플레이,2016년 상반기,생산·제조,생산관리·공정관리·품질관리,수도권4년,"['학점 3.8/4.5', '토익 895', '토스 Level6', '오픽 M1',...",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
2,3,자연/공학/의약계열,IT/컴퓨터공학,롯데IT테크(주),2015년 하반기,IT·인터넷,응용프로그래머,수도권4년,"['학점 3.5/4.5', '토익 780', '토스 Level4']",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
3,4,인문/사회계열,인문계열(기타),홈플러스(주),2022년 하반기,영업·고객상담,판매·서빙·매장관리,대졸4년,"['학점 4.5/4.5', '제2외국어 3개', '자격증 4개', '해외경험 1회'...",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
4,5,인문/사회계열,경영학,㈜노루페인트,2015년 상반기,마케팅·광고·홍보,마케팅·광고·분석,지방4년,"['학점 3.7/4.5', '토익 825', '자격증 1개', '인턴 1회', '수...",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
...,...,...,...,...,...,...,...,...,...,...,...
7122,7123,자연/공학/의약계열,IT/컴퓨터공학,㈜티맥스소프트,2015년 상반기,IT·인터넷,응용프로그래머,수도권4년,"['학점 3.3/4.5', '토익 865', '토스 Level6', '수상 1회']",-1.0,None
7123,7124,자연/공학/의약계열,IT/컴퓨터공학,GS리테일,2015년 상반기,IT·인터넷,시스템프로그래머,수도권4년,"['학점 3.7/4.5', '토익 735', '오픽 IH', '자격증 4개', '해...",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
7124,7125,인문/사회계열,경제학,㈜하나투어,2015년 하반기,영업·고객상담,영업관리·지원·영업기획,서울4년,"['학점 3/4.5', '토익 840', '토스 Level6', '자격증 4개']",-1.0,None
7125,7126,인문/사회계열,역사/한국사학,현대백화점,2019년 하반기,마케팅·광고·홍보,마케팅·광고·분석,지방4년,"['학점 4/4.5', '토익 965', '오픽 IH', '자격증 3개', '수상 ...",2.0,https://www.jobkorea.co.kr/starter/PassAssay/V...
7126,7127,인문/사회계열,경제학,신한카드(주),2015년 하반기,영업·고객상담,고객상담·인바운드,지방4년,"['학점 3.9/4.5', '토익 690', '자격증 4개', '자원봉사 1회']",-1.0,https://www.jobkorea.co.kr/starter/PassAssay/V...

In [59]:
answer_data.columns = ['doc_id', 'answer_id', 'question', 'answer', 'doc_url', 'summary', 'question_category', 'view', 'doc_score', 'pro_good_cnt', 'pro_bad_cnt']

In [61]:
answer_data.to_csv('answer_3_0.csv')

In [63]:
user_data.to_csv('document_3_0.csv')

In [67]:
np.isnan(answer_data['view'].unique()).sum()

0

In [ ]:
answer_data